coverage (#5)
* refactoring code + add migration flyway

* add constants and error

* add errors and test

* add loggers and exception

* fix package language

* refactor user service test

* fix workflows

* add profiles and fix workflows

* fix workflows

* fix workflows

* fix workflows

* add config to workflows

* add config to workflows

* add config to workflows

* add sonar maven

* add sonar maven

* add sonar maven

* restore

* restore

* add dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix config dockerfile

* fix version node to worflows

* add sonar to worflows

* add sonar to worflows

* add sonar to worflows

* fix workflows

* fix workflows

* fix workflows

* fix workflows

* fix sonar pom

* fix sonar pom and workflow

* fix pom and rename workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* fix config sonar to workflows

* new config sonat to workflows

* fix format workflows

* fix format workflows

* fix format workflows

* refactor code to sonar

* add jacoco

* add jacoco properties

* add maven surefire

* add maven surefire

* add maven surefire

* add maven surefire

* add maven surefire

* add maven surefire

* add lombok config

* add lombok config

* add config pom

diff --git a/.github/workflows/pipe-PR-verify.yml b/.github/workflows/pipe-PR-verify.yml
--- a/.github/workflows/pipe-PR-verify.yml
+++ b/.github/workflows/pipe-PR-verify.yml
@@ -31,6 +31,13 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
+      - name: Check for lombok.config
+        run: |
+            if [ ! -f "lombok.config" ]; then
+              echo "WARNING: lombok.config file not found."
+              exit 1
+            fi
+
       - name: Build with Maven
         run: mvn -B clean verify -DskipTests
 
@@ -80,7 +87,7 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
         run: |
-          JACOCO_REPORT_PATH="$GITHUB_WORKSPACE/target/site/jacoco-aggregate/jacoco.xml"
+          JACOCO_REPORT_PATH="target/site/jacoco-aggregate/jacoco.xml"
           mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.coverage.jacoco.xmlReportPaths=$JACOCO_REPORT_PATH
 
   docker:
